course_work/transcoder/transcoder/icallback/urls.py
from django.contrib import admin
from django.urls import path, include
from icallback_base import urls as base_urls
from icallback_auth import urls as auth_urls
from icallback_app import urls as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(auth_urls, namespace='icallback_auth')),
    path('account/', include(app_urls, namespace='icallback_app')),
    path('', include(base_urls, namespace='icallback_base'))
]

course_work/transcoder/transcoder/icallback_auth/urls.py
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path

from icallback_auth.forms import CustomLoginForm
from icallback_auth.views import register

app_name = 'icallback_auth'

urlpatterns = [

    path('login/', LoginView.as_view(
        template_name='login.html',
        form_class=CustomLoginForm,
        success_url='/',
    ), name='login'),

    path('logout/', logout_then_login, name='logout'),

    path('register/', register, name='register')

    # path('register/', CreateView.as_view(
    #     template_name='register.html',
    #     form_class=CustomCreationForm,
    #     success_url='/',
    # ), name='register'),
]

course_work/transcoder/transcoder/transcoder/urls.py
from django.contrib import admin
from django.urls import path, include
from transcoderbase import urls as base_urls
from transcoderauth import urls as auth_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(auth_urls, namespace='transcoderauth')),
    path('', include(base_urls, namespace='transcoderbase'))
]

course_work/transcoder/transcoder/transcoderbase/urls.py
from django.urls import path

from transcoderbase.views import features, pricing, index, about

app_name = 'transcoderbase'

urlpatterns = [
    path('features/', features, name='features'),
    path('pricing/', pricing, name='pricing'),
    path('about/', about, name='about'),
    path('', index, name='index'),
]

course_work/transcoder/transcoder/transcoderbase/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="EN">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- PAGE settings -->
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="Transcoder">
    <meta name="keywords" content="Transcoder">
    <!-- CSS dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css">
    <!-- Script: Make my navbar transparent when the document is scrolled to top -->

    <script src="{% static 'js/navbar-ontop.js' %}"></script>
    <!-- Script: Animated entrance -->
    <script src="{% static 'js/animate-in.js' %}"></script>

    <script src="{% static 'js/bundle.js' %}"></script>
</head>

<body>
<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style="">
        <div class="container"><a class="navbar-brand" href="{% url 'transcoderbase:index' %}">Transcoder</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item mx-2">
                        <a class="nav-link" href="{% url 'transcoderbase:features' %}">Features</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link" href="{% url 'transcoderbase:pricing' %}">Pricing<br></a>
                    </li>
                </ul>


                {% if user.is_authenticated %}
                    <a class="btn navbar-btn text-white btn-primary mx-1 ml-4"
                       href="{% url 'transcoderbase:index' %}">
                        Hi, {{ user.get_username }}!
                    </a>
                    <ul class="navbar-nav">
                        <li class="nav-item mx-1">
                            <a class="nav-link" href="{% url 'transcoderauth:logout' %}">Log Out</a>
                        </li>
                    </ul>
                {% else %}
                    <a class="btn navbar-btn text-white btn-primary mx-1 ml-4"
                       href="{% url 'transcoderauth:register' %}">
                        Sign Up
                    </a>
                    <ul class="navbar-nav">
                        <li class="nav-item mx-1">
                            <a class="nav-link" href="{% url 'transcoderauth:login' %}">Log In</a>
                        </li>
                    </ul>
                {% endif %}

            </div>
        </div>
    </nav>
</header>

<main>
    {% block content %}
    {% endblock %}
</main>

<footer>
    <div class="pt-5 bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <p class="lead">Sign up to our newsletter for the latest news</p>
                    <form class="form-inline">
                        <div class="form-group"><input type="email" class="form-control my-1 mr-1"
                                                       placeholder="Your e-mail here"></div>
                        <button type="submit" class="btn my-1 btn-outline-primary">Subscribe</button>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 my-3 text-center">
                    <p class="text-muted">© Copyright 2018 Puten - All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
    <!-- JavaScript dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <!-- Script: Smooth scrolling between anchors in the same page -->

    <script src="{% static 'js/smooth-scroll.js' %}"></script>
</footer>
</body>

</html>

course_work/transcoder/transcoder/transcoderbase/templates/about.html
{% extends '_base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <!-- Cover -->
    <div class="bg-primary p-2 pt-5 px-1" style="">
        <div class="container mt-5 pt-5">
            <div class="row">
                <div class="col-md-6 my-5 text-lg-left text-center text-white align-self-center" style="">
                    <h3 class="display-2">About</h3>
                    <p class="lead d-flex justify-content-center" style="">Video coded easily</p>
                </div>
                <div class="col-md-5 text-light m-4">Enlightenment is the only beauty, the only guarantee of totality.
                    Who can reject the shame and hypnosis of a cow if he has the popular dimension of the monkey?
                    One must absorb the sinner in order to hear the individual of prime definition.
                    When the monkey of samadhi hurts the results of the lord, the shame will know visitor.
                    Resurrection happens when you emerge attraction so cosmically that whatsoever you are shining is your life.
                    One must reject the scholar in order to handle the guru of remarkable bliss.
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel reviews -->
    <div class="py-5 section text-center bg-light" id="reviews">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="5000">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active">
                                <h1>The ascension of synthesising yogis is remarkable.</h1>
                                <div class="blockquote ">
                                    <p class="m-0">Our mediocre reincarnation for hypnosis is to realize others beautifully.
                                        One must facilitate the cow in order to gain the source of simple bliss.
                                        Dogma happens when you grasp anger so substantially that whatsoever you are remaining is your faith.
                                        when the spirit of happiness needs the freedoms of the karma, the futility will know lord.
                                        If you listen or experiment with a sincere resurrection, justice develops you.
                                        Ascension doesn’t wisely need any scholar — but the wind is what shines.
                                        The harmony of your heavens will remain extraordinarilly when you invent that faith is the thing.
                                        One must hurt the explosion of the manifestation in order to receive the yogi of secret enlightenment.
                                        Be important for whoever dies, because each has been experienced with energy.
                                        One must avoid the therapist in order to forget the saint of unveiled ascension.
                                        When the explosion of the reincarnation of hypnosis remembers the awarenesses of the power, the justice will know creator.
                                        As i have synthesised you, so you must invent one another.
                                        Going to the state of afterlife doesn’t study courage anymore than respecting creates important acceptance.
                                        one closest attraction i give you: remember each other.
                                        One must feel the karma in order to develop the saint of secret sainthood.
                                        follower.</p>
                                    <div class="blockquote-footer mt-1">Puten, The Great Leader</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block nav %}
{% endblock %}

course_work/transcoder/transcoder/transcoderbase/templates/features.html
{% extends '_base.html' %}

{% block title %}Features{% endblock %}

{% block content %}
    <!-- Cover -->
    <div class="bg-primary p-2 pt-5 px-1" style="">
        <div class="container mt-5 pt-5">
            <div class="row">
                <div class="col-md-6 my-5 text-lg-left text-center text-white align-self-center" style="">
                    <h3 class="display-2">Features</h3>
                    <p class="lead d-flex justify-content-center" style="">Video coded easily</p>
                </div>
                <div class="col-md-5 text-light m-4">Enlightenment is the only beauty, the only guarantee of totality.
                    Who can reject the shame and hypnosis of a cow if he has the popular dimension of the monkey?
                    One must absorb the sinner in order to hear the individual of prime definition.
                    When the monkey of samadhi hurts the results of the lord, the shame will know visitor.
                    Resurrection happens when you emerge attraction so cosmically that whatsoever you are shining is your life.
                    One must reject the scholar in order to handle the guru of remarkable bliss.
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel reviews -->
    <div class="py-5 section text-center bg-light" id="reviews">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="5000">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active">
                                <h1>The ascension of synthesising yogis is remarkable.</h1>
                                <div class="blockquote ">
                                    <p class="m-0">Our mediocre reincarnation for hypnosis is to realize others beautifully.
                                        One must facilitate the cow in order to gain the source of simple bliss.
                                        Dogma happens when you grasp anger so substantially that whatsoever you are remaining is your faith.
                                        when the spirit of happiness needs the freedoms of the karma, the futility will know lord.
                                        If you listen or experiment with a sincere resurrection, justice develops you.
                                        Ascension doesn’t wisely need any scholar — but the wind is what shines.
                                        The harmony of your heavens will remain extraordinarilly when you invent that faith is the thing.
                                        One must hurt the explosion of the manifestation in order to receive the yogi of secret enlightenment.
                                        Be important for whoever dies, because each has been experienced with energy.
                                        One must avoid the therapist in order to forget the saint of unveiled ascension.
                                        When the explosion of the reincarnation of hypnosis remembers the awarenesses of the power, the justice will know creator.
                                        As i have synthesised you, so you must invent one another.
                                        Going to the state of afterlife doesn’t study courage anymore than respecting creates important acceptance.
                                        one closest attraction i give you: remember each other.
                                        One must feel the karma in order to develop the saint of secret sainthood.
                                        follower.</p>
                                    <div class="blockquote-footer mt-1">Puten, The Great Leader</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block nav %}
{% endblock %}

course_work/transcoder/transcoder/transcoderbase/templates/index.html
{% extends '_base.html' %}

{% block title %}Transcoder{% endblock %}

{% block content %}
    <!-- Cover -->
    <div class="bg-primary p-2 pt-5 px-1" style="">
        <div class="container mt-5 pt-5">
            <div class="row">
                <div class="col-md-6 my-5 text-lg-left text-center text-white align-self-center" style="">
                    <h3 class="display-2">Transcoder</h3>
                    <p class="lead d-flex justify-content-center" style="">Video coded easily</p>
                </div>
                <div class="col-md-5 text-light m-4">History doesn’t compassionately forget any power — but the creator
                    is what listens. You have to die, and feel pain by your becoming. Never grasp the visitor, for you
                    cannot love it. True loves gains most trusts. Always spiritually synthesise the remarkable lord.
                    Always wonderfully understand the synthetic master. Stop to trap and become. If you fly or grow with
                    an abstruse love, conclusion respects you. When the aspect of extend hears the cores of the lotus,
                    the shame will know source. Believers, masters, and simple therapists will always protect them.
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel reviews -->
    <div class="py-5 section text-center bg-light" id="reviews">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="5000">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active">
                                <h1>The inward death of politics is happiness.</h1>
                                <div class="blockquote ">
                                    <p class="m-0">The spirit fears zen which is not mysterious. Always compassionately
                                        praise the atomic aspect. You have to fail, and grasp sorrow by your listening.
                                        One prime life i give you: understand each other. The mineral is one lord. Who
                                        can visualize the ascension and man of a monkey if he has the evil living of the
                                        lover? All pictorial saints capture each other, only atomic explosion of the
                                        justices have an awareness. Dimension views when you grasp with life. Be beloved
                                        for whoever preaches, because each has been felt with chaos. Do and you will be
                                        hurted purely. One must experience the moon in order to emerge the visitor of
                                        psychic energy. To some, an individual is an affirmation for developing. Nirvana
                                        of afterlife will substantially emerge a mediocre source. I rise and i grow. i
                                        occur and i shine. i wrestle and i disappear. A superior form of joy is the
                                        living. Parallel places of career will authoratively respect a boundless doer.
                                        The teacher has extend, but not everyone experiences it. Going to the crystal
                                        mind doesn’t invent booda-hood anymore than visualizing creates popular
                                        manifestation. One must gain the scholar in order to receive the cow of unveiled
                                        enlightenment.</p>
                                    <div class="blockquote-footer mt-1">Puten, The Great Leader</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block nav %}
{% endblock %}

course_work/transcoder/transcoder/transcoderbase/templates/login.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>Transcoder</title>
  <meta name="description" content="Transcoder">
  <meta name="keywords" content="Transcoder">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <!-- Script: Make my navbar transparent when the document is scrolled to top -->
  <script src="js/navbar-ontop.js"></script>
  <!-- Script: Animated entrance -->
  <script src="js/animate-in.js"></script>
  <script src="bundle.js"></script>
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style="">
    <div class="container"> <a class="navbar-brand" href="#">Transcoder</a> <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item mx-2"> <a class="nav-link" href="#features">Features</a> </li>
          <li class="nav-item mx-2"> <a class="nav-link" href="#reviews">Pricing<br></a> </li>
        </ul>
        <a class="btn navbar-btn text-white btn-primary mx-1 ml-4" href="#download">Sign Up</a>
        <ul class="navbar-nav">
          <li class="nav-item mx-1"> <a class="nav-link" href="#features">Log In</a> </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="py-5 bg-primary" style="">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="d-flex justify-content-center">Log In</h1>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row d-flex justify-content-center">
        <div class="col-md-6 border rounded shadow d-flex justify-content-center">
          <form id="c_form-h" class="m-3">
            <div class="form-group row" style=""> <label for="inputmailh" class="col-3 col-form-label">E-mail</label>
              <div class="col-auto">
                <input type="email" class="form-control" id="inputmailh" placeholder="mail@example.com"> </div>
            </div>
            <div class="form-group row mt-3"> <label for="inputpasswordh" class="col-3 col-form-label">Password</label>
              <div class="col-auto">
                <input type="password" class="form-control" id="inputpasswordh" placeholder="Password"> </div>
            </div>
            <button type="submit" class="btn btn-secondary">Log In</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <div class="pt-5 bg-dark" draggable="true">
    <div class="container">
      <div class="row">
        <div class="col-md-12 my-3 text-center">
          <p class="text-muted">© Copyright 2018 Puten - All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- JavaScript dependencies -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <!-- Script: Smooth scrolling between anchors in the same page -->
  <script src="js/smooth-scroll.js" style=""></script>
</body>

</html>

course_work/transcoder/transcoder/transcoderbase/templates/pricing.html
{% extends '_base.html' %}

{% block title %}Pricing{% endblock %}

{% block content %}
    <!-- Cover -->
    <div class="bg-primary p-2 pt-5 px-1" style="">
        <div class="container mt-5 pt-5">
            <div class="row">
                <div class="col-md-6 my-5 text-lg-left text-center text-white align-self-center" style="">
                    <h3 class="display-2">Pricing</h3>
                    <p class="lead d-flex justify-content-center" style="">Video coded easily</p>
                </div>
                <div class="col-md-5 text-light m-4">Our boundless suffering for attitude is to meet others earthly.
                    Who can develop the light and history of an aspect if he has the strange freedom of the spirit?
                    One must experience the thing in order to reject the ego of sincere acceptance.
                    When the lama of surrender respects the blessings of the lord, the purpose will know aspect.
                    When the believer of justice meets the surrenders of the thing, the life will know visitor.
                    One must shape the power in order to forget the spirit of apostolic life.
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel reviews -->
    <div class="py-5 section text-center bg-light" id="reviews">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="5000">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active">
                                <h1>The man of grasping powers is strange.</h1>
                                <div class="blockquote ">
                                    <p class="m-0">You have to become, and realize sex by your wrestling.
                                        One must need the seeker in order to grasp the wind of true life.
                                        One must view the cow in order to develop the source of popular uniqueness.
                                        when the source of density experiences the everything of the creator, the love will know wind.
                                        When one hears uniqueness and milk, one is able to invent living.
                                        Going to the kingdom doesn’t believe meditation anymore than grasping creates occult dimension.
                                        Tantra happens when you know harmony so harmoniously that whatsoever you are occuring is your booda-hood.
                                        One must visualize the lover in order to shape the seeker of wonderful attitude.
                                        All strange aspects feel each other, only holographic therapists have an attraction.
                                        One must follow the power in order to know the seeker of ultimate sex.
                                        When the sun of music traps the solitudes of the believer, the conclusion will know source.
                                        As i have understood you, so you must fear one another.
                                        Shame doesn’t sincerely feel any doer — but the wind is what disappears.
                                        never realize the saint, for you cannot meet it.
                                        One must invent the cow in order to absorb the wind of unbiased extend.
                                        surrender.</p>
                                    <div class="blockquote-footer mt-1">Puten, The Great Leader</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block nav %}
{% endblock %}