course_work/transcoder/transcoder/icallback/urls.py
from django.contrib import admin
from django.urls import path, include
from icallback_base import urls as base_urls
from icallback_auth import urls as auth_urls
from icallback_app import urls as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(auth_urls, namespace='icallback_auth')),
    path('account/', include(app_urls, namespace='icallback_app')),
    path('', include(base_urls, namespace='icallback_base'))
]

course_work/transcoder/transcoder/icallback_app/urls.py
from django.urls import path

from icallback_app.views import settings, account, widget_delete, widget_toggle

app_name = 'icallback_app'

urlpatterns = [
    path('calls/', account, name='calls', kwargs={"active": "calls"}),
    path('widgets/', account, name='widgets', kwargs={"active": "widgets"}),
    path('statistics/', account, name='statistics', kwargs={"active": "statistics"}),
    path('settings/', settings, name='settings'),
    path('widget/delete/<int:widget_id>', widget_delete, name='widget_delete'),
    path('widget/toggle/<int:widget_id>', widget_toggle, name='widget_toggle'),
]

course_work/transcoder/transcoder/transcoder/urls.py
from django.contrib import admin
from django.urls import path, include
from transcoderbase import urls as base_urls
from transcoderauth import urls as auth_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(auth_urls, namespace='transcoderauth')),
    path('', include(base_urls, namespace='transcoderbase'))
]

course_work/transcoder/transcoder/icallback_app/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

from enum import Enum

# Create your models here.
from django.db.models import Manager

from helpers.model_helpers import list_enum


class Widget(models.Model):
    user = models.ForeignKey(User, related_name='widgets', on_delete=models.PROTECT, null=True, blank=True)

    site_name = models.CharField(max_length=140, blank=True)

    widget_key = models.CharField(max_length=140, blank=True, default=uuid.uuid1)
    active = models.BooleanField(default=False)

    objects = Manager()

    def __str__(self):
        return 'Widget [%s]' % self.site_name


class CallStatusType(Enum):
    OPERATOR_ANSWERED = "OPERATOR_ANSWERED"
    CLIENT_ANSWERED = "CLIENT_ANSWERED"
    NO_ANSWER = "NO_ANSWER"
    FAILED = "FAILED"


class Call(models.Model):
    callId = models.CharField(max_length=140, blank=True)

    user = models.ForeignKey(User, related_name='calls', on_delete=models.PROTECT, null=True, blank=True)
    widget = models.ForeignKey(Widget, related_name='calls', on_delete=models.PROTECT, null=True, blank=True)

    client_number = models.CharField(max_length=140, blank=True, null=True)
    operator_number = models.CharField(max_length=140, blank=True, null=True)

    status = models.CharField(max_length=140, choices=list_enum(CallStatusType), null=True)

    time_created = models.DateTimeField(auto_now_add=True, null=True)
    time_started = models.DateTimeField(default=None, null=True)
    time_answered = models.DateTimeField(default=None, null=True)
    time_ended = models.DateTimeField(default=None, null=True)

course_work/transcoder/transcoder/icallback_app/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from icallback_app.models import Widget


class WidgetCreationForm(ModelForm):
    class Meta:
        model = Widget
        fields = ('site_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['site_name'].label = "Site"
        self.fields['site_name'].help_text = "www.my-site.com"

    def clean(self):
        data = self.cleaned_data

        if len(data['site_name']) == 0:
            raise ValidationError('Site is empty!')

        return data

    def save(self, commit=True):
        inst = super().save(commit)

        print(inst)

        return inst

course_work/transcoder/transcoder/icallback_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from helpers.django_request_helpers import django_get, django_get_or_post
from icallback_app.forms import WidgetCreationForm
from icallback_app.models import Widget, Call


@login_required
@django_get_or_post
def account(request, active):
    widgets = Widget.objects.filter(user=request.user.id).all()
    calls = Call.objects.filter(user=request.user.id).all()

    if request.method == 'POST':
        widget_form = WidgetCreationForm(request.POST)
        if widget_form.is_valid():
            widget = widget_form.save(commit=False)
            widget.user = request.user
            widget.save()
            widget_form = WidgetCreationForm()
    else:
        widget_form = WidgetCreationForm()

    return render(request, 'account.html', {
        "active_tab": active,
        "widgets": widgets,
        "widget_form": widget_form,
        "calls": calls,
    })


@login_required
@django_get
def settings(request):
    return render(request, 'settings.html')


@login_required
@django_get
def widget_delete(request, widget_id):
    print("toggling", widget_id)
    widget_to_delete = Widget.objects.get(pk=widget_id)

    if widget_to_delete:
        widget_to_delete.delete()
    else:
        pass  # TODO: throw an error

    return redirect('icallback_app:widgets')


@login_required
@django_get
def widget_toggle(request, widget_id):
    widget_to_toggle = Widget.objects.get(pk=widget_id)

    if widget_to_toggle:
        widget_to_toggle.active = not widget_to_toggle.active
        widget_to_toggle.save()
    else:
        pass  # TODO: throw an error

    return redirect('icallback_app:widgets')

course_work/transcoder/transcoder/icallback_app/templates/account.html
{% extends '_base.html' %}

{% block title %}Account{% endblock %}

{% block content %}
    <div class="container mt-3 mb-3 pt-5 p-2">
        <div class="row">
            <div class="col-md-12 border p-2">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link {% if active_tab == "calls" %}active show{% endif %}"
                           href="{% url 'icallback_app:calls' %}"
{#                           data-toggle="tab" data-target="#tabone"#}
                        >
                            Calls
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if active_tab == "widgets" %}active show{% endif %}"
                           href="{% url 'icallback_app:widgets' %}"
{#                           data-toggle="tab" data-target="#tabtwo"#}
                        >
                            Widgets
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if active_tab == "statistics" %}active show{% endif %}"
                           href="{% url 'icallback_app:statistics' %}"
{#                           data-toggle="tab" data-target="#tabthree"#}
                        >
                            Statistics
                        </a>
                    </li>
                </ul>
                <div class="tab-content mt-2">
                    <div class="tab-pane fade  {% if active_tab == "calls" %}active show{% endif %}"
                         id="tabone" role="tabpanel">
                        {% include "calls.html" %}
                    </div>
                    <div class="tab-pane fade {% if active_tab == "widgets" %}active show{% endif %}"
                         id="tabtwo" role="tabpanel">
                        {% include "widgets.html" %}
                    </div>
                    <div class="tab-pane fade  {% if active_tab == "statistics" %}active show{% endif %}"
                         id="tabthree" role="tabpanel">
                        {% include "statistics.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block nav %}
{% endblock %}

course_work/transcoder/transcoder/icallback_app/templates/calls.html
<h2 class="ml-2 pt-1">Widgets</h2>

<div class="container">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>id</th>
                <th>Call Date</th>
                <th>Client Number</th>
                <th>Operator Number</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody>


            {% for call in calls %}
                <tr>
                    <td>{{ call.callId }}</td>

                    <td>{{ call.time_created }}</td>
                    <td>{{ call.client_number }}</td>
                    <td>{{ call.operator_number }}</td>
                    <td>{{ call.status }}</td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

course_work/transcoder/transcoder/icallback_app/templates/settings.html
{% extends '_base.html' %}

{% block title %}Settings{% endblock %}

{% block content %}
    <div class="container mt-3 mb-3 pt-5 p-2">
        <div class="row">
            <div class="col-md-12 border p-2">
                <div class="container m-2">
                    <div class="row">
                        <h1>Settings</h1>
                    </div>
                    <div class="row text-muted">
                        Under construction
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block nav %}
{% endblock %}

course_work/transcoder/transcoder/icallback_app/templates/statistics.html
<h2 class="ml-2 pt-1">Statistic</h2>
<div class="text-muted ml-2">under construction</div>

course_work/transcoder/transcoder/icallback_app/templates/widgets.html
{% load widget_tweaks %}

<h2 class="ml-2 pt-1">Widgets</h2>
<div class="container">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Site</th>
                <th>Key</th>
                <th>Active</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            {% for widget in widgets %}
                <tr>
                    <td>{{ widget.site_name }}</td>
                    <td>{{ widget.widget_key }}</td>
                    <td>
                        <a href="{% url 'icallback_app:widget_toggle' widget_id=widget.id %}">
                            {{ widget.active | yesno:"Active,Not active" }}
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'icallback_app:widget_delete' widget_id=widget.id %}">DELETE</a>
                    </td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

    <div class="container col-lg-8">
        <div class="card">
            <div class="card-header"> Add a new widget</div>
            <div class="card-body">
                <form method="post" id="c_form-h" class="" novalidate action="{% url 'icallback_app:widgets' %}">
                    {% csrf_token %}

                    <span class="text-warning">
                    {{ widget_form.non_field_errors }}
                    </span>

                    {% for hidden_field in widget_form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                    {% endfor %}

                    {% for field in widget_form.visible_fields %}
                        <div class="form-group row">
                            <label for="{{ field.name }}" class="col-2 col-form-label">{{ field.label }}</label>
                            <div class="col-auto">
                                {% if widget_form.is_bound %}
                                    {% if field.errors %}
                                        {% render_field field class="form-control is-invalid" placeholder=field.help_text id=field.name %}
                                    {% else %}
                                        {% render_field field class="form-control is-valid" placeholder=field.help_text id=field.name %}
                                    {% endif %}
                                {% else %}
                                    {% render_field field class="form-control" placeholder=field.help_text id=field.name %}
                                {% endif %}
                            </div>
                            {% if widget_form.is_bound and field.errors %}
                                {% for error in field.errors %}
                                    <div class="text-danger ml-2 mt-1">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
        </div>
    </div>
</div>